#! /usr/bin/env node
import inquirer from 'inquirer';

// defining function named as generateRandomNumber to generate a random number between min and max.
function generate_random_number(minimum: number, maximum: number): number {
    return Math.floor(Math.random() * (maximum - minimum + 1)) + minimum;
}

// defining function for checking the user's guess against the secret number
function checkGuess(num: number, secret_number: number, attempts: number, max_attempts: number): string {
    // incrmenting attempts one by one till it reaches the max attempt limit
    attempts++;

    // Checking if max_attempts is reached
    if (attempts >= max_attempts) {
        // Printing sorry message if max attempts limit is reached
        return `Sorry, you've run out of attempts. The correct number was ${secret_number}.`;
    } else {
        // Printing congratulation message if the user guessed the correct answer.
        if (num === secret_number) {
            return `Congratulations! You have guess the correct number (${secret_number}) in ${attempts} attempts.`;
        } else if (num < secret_number) {
            // Printing too low message if the user guessed number is too low than the actual number generated by computer using Math.random function
            return "Too low. Please Try again.";
        } else {
            // Printing too high message if the user guessed number is too high than the actual number generated by computer using Math.random function
            return "Too high. Please Try again.";
        }
    }
}

// defining function for start playing the game
async function playGame() {
    //defining the minimum and maximum numbers range
    const min = 1;
    const max = 100;
     // Generating a secret number within the defined range using the above function named as generateRandomNumber
    const secretNumber = generate_random_number(min, max);
    let attempts = 0;

    //defining the max number of attempts allowed
    const maxAttempts = 6;

    console.log("----------------------------------------")
    console.log("Welcome to ahmed's number guessing game!");
    console.log("Guess a number between 1 and 100.");

    //while loop for prompting the player to choose guesses
    while (attempts < maxAttempts) {
        const { guess } = await inquirer.prompt({
            type: 'number',
            name: 'guess',
            message: 'Plz enter your guess:'
        });

        //checking the player guess and according to that guess displaying the result
        const result = checkGuess(guess, secretNumber, attempts, maxAttempts);
        console.log(result);

         // exiting the loop If the game is over with either won or lost.
        if (result.startsWith('Congratulations') || result.startsWith('Sorry')) {
            break;
        } else {
            // Incrementing the attempts counter if the game is still ongoing
            attempts++;
        }
    }
// Exit the game
    process.exit();
}
//calling function for start playing game
playGame();
